# -*- coding: utf-8 -*-
"""TesteLivroPAC7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VKI5dRWULwy3_HBOWGhNwBWn_EFEL9C2
"""

import requests
import json

books = ["1984", "To Kill a Mockingbird", "The Catcher in the Rye"]

# Busca as informações dos livros na API do Google Books
book_infos = []
for book in books:
    url = f"https://www.googleapis.com/books/v1/volumes?q={book}"
    response = requests.get(url)
    data = json.loads(response.text)
    if data["totalItems"] > 0:
        book_info = data["items"][0]["volumeInfo"]
        book_infos.append(book_info)

# Pega as informações relevantes dos livros
relevant_info = []
for book_info in book_infos:
    info = {
        "title": book_info.get("title", ""),
        "author": book_info.get("authors", [""])[0],
        "genre": book_info.get("categories", [""])[0],
        "synopsis": book_info.get("description", ""),
    }
    relevant_info.append(info)

# Busca por livros semelhantes
similar_books = []
for i, book1 in enumerate(relevant_info):
    for j, book2 in enumerate(relevant_info):
        if i != j:
            similarity_score = 0
            if book1["title"].lower() != book2["title"].lower():
                similarity_score += 1
            if book1["author"].lower() != book2["author"].lower():
                similarity_score += 1
            if book1["genre"].lower() != book2["genre"].lower():
                similarity_score += 1
            if book1["synopsis"].lower() != "" and book1["synopsis"].lower() in book2["synopsis"].lower():
                similarity_score += 1
            if similarity_score >= 2 and book2 not in similar_books:
                similar_books.append(book2)

# Imprime os livros semelhantes encontrados
if len(similar_books) > 0:
    print("Livros semelhantes encontrados:")
    for book in similar_books:
        print("Título: ", book["title"])
        print("Autor: ", book["author"])
        print("Gênero: ", book["genre"])
        print("Sinopse: ", book["synopsis"])
        print()
else:
    print("Não foram encontrados livros semelhantes.")